
export const ALL_PROPERTIES_REQUEST = "ALL_PROPERTIES_REQUEST"
export const ALL_PROPERTIES_SUCCESS = "ALL_PROPERTIES_SUCCESS"
export const ALL_PROPERTIES_FAIL = "ALL_PROPERTIES_FAIL"


export const SINGLE_PROPERTY_REQUEST = "SINGLE_PROPERTY_REQUEST"
export const SINGLE_PROPERTY_SUCCESS = "SINGLE_PROPERTY_SUCCESS"
export const SINGLE_PROPERTY_FAIL = "SINGLE_PROPERTY_FAIL"


export const ALL_AGENTS_REQUEST = "ALL_AGENTS_REQUEST"
export const ALL_AGENTS_SUCCESS = "ALL_AGENTS_SUCCESS"
export const ALL_AGENTS_FAIL = "ALL_AGENTS_FAIL"


export const SINGLE_AGENT_REQUEST = "SINGLE_AGENT_REQUEST"
export const SINGLE_AGENT_SUCCESS = "SINGLE_AGENT_SUCCESS"
export const SINGLE_AGENT_FAIL = "SINGLE_AGENT_FAIL"


export const ALL_PROJECTS_REQUEST = "ALL_PROJECTS_REQUEST"
export const ALL_PROJECTS_SUCCESS = "ALL_PROJECTS_SUCCESS"
export const ALL_PROJECTS_FAIL = "ALL_PROJECTS_FAIL"


export const SINGLE_PROJECT_REQUEST = "SINGLE_PROJECT_REQUEST"
export const SINGLE_PROJECT_SUCCESS = "SINGLE_PROJECT_SUCCESS"
export const SINGLE_PROJECT_FAIL = "SINGLE_PROJECT_FAIL"



export const ALL_BLOGS_REQUEST = "ALL_BLOGS_REQUEST"
export const ALL_BLOGS_SUCCESS = "ALL_BLOGS_SUCCESS"
export const ALL_BLOGS_FAIL = "ALL_BLOGS_FAIL"


export const SINGLE_BLOG_REQUEST = "SINGLE_BLOG_REQUEST"
export const SINGLE_BLOG_SUCCESS = "SINGLE_BLOG_SUCCESS"
export const SINGLE_BLOG_FAIL = "SINGLE_BLOG_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"